{% set name = "httpcore" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9fc092e4799b26174648e54b74ed5f683132a464e95643b226e00c2ed2fa6535

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '
  skip: True  # [py<36 or s390x]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - h11 >=0.11,<0.13
    - h2 >=3,<5
    - sniffio ==1.*
    - anyio ==3.*
    - certifi

test:
  requires:
    - pip
  imports:
    - httpcore
  commands:
    - pip check || true  # [not win]
    - pip check || 1     # [win]

about:
  home: https://github.com/encode/httpcore
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The next generation HTTP client.

extra:
  recipe-maintainers:
    - nicoddemus
    - synapticarbors
