travis:
  secure:
    BINSTAR_TOKEN: XvpBKxYmdtrwJLePIt8XEq4ywKo31QvgGSpoB/6A3S+uFauHDFrqE+oaCr/N56gg+wPml6Xs6L7NS7fuCIzKv7s+vLRpCKD7ettAtpDzQbwO1AWmZZyaiiLRifpnXwcI+aYsGYcyH4nLtjSgaV/Q7lswVKjgC4IV7l/7klX7qtt6ehs3QrkysVz5GAtp/4RrqAMwtOAuvtv++86DXZfEVq/4nzLA6bgR+cMAmE9k1+yDcr2bXrw+m/YrO8tyxEMOhgtwm3B3ZwOf8gnNyJdig1NxXgxA+h4I5rG0uFSaN59IW9/+ZQ5FF9v/aP9cMkqmHjoCQBCe0jbhXoTZ1j7kIV2JDN1NfZbessypsi01om2Cu4UhoJyuPWwNygAcIsSuyKe84Axg5LgeXdGdhnhuEd7LPrHpNjZPHRbKc/wtaTxPQMxBhUs7aC8XAN+c8fx0385qViWaXYShnHFE3pUBRLc0FEm00NTsjx9D6aSIMvALaGoAwCjY6WU8P09ox++xSYbcrr3maHozkYr83p7gE5WiXYs5m75Uhb8xED5FB8tqGr8Q5trIDZG+s+KrjcWOJySj/n/UInxNtuYI5PNDfbXRhTYVf6NVsY/TyNBGZrHibEHuBS41s2//8AkKTHfBMzyivgE/6fgcxg0PI8+cZQ1OEAjSt0N4HkECn5ZZD0c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
